config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :authors

  resources :editions

  resources :universes

  resources :entities

  resources :locations

  resources :properties

  resources :publishers

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/edition.rb
class Edition < ActiveRecord::Base
  belongs_to :author
  belongs_to :publisher
  belongs_to :universe
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_action :set_edition, only: [:show, :edit, :update, :destroy]

  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.all
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
  end

  # GET /editions/new
  def new
    @edition = Edition.new
  end

  # GET /editions/1/edit
  def edit
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(edition_params)

    respond_to do |format|
      if @edition.save
        format.html { redirect_to @edition, notice: 'Edition was successfully created.' }
        format.json { render :show, status: :created, location: @edition }
      else
        format.html { render :new }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /editions/1
  # PATCH/PUT /editions/1.json
  def update
    respond_to do |format|
      if @edition.update(edition_params)
        format.html { redirect_to @edition, notice: 'Edition was successfully updated.' }
        format.json { render :show, status: :ok, location: @edition }
      else
        format.html { render :edit }
        format.json { render json: @edition.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition.destroy
    respond_to do |format|
      format.html { redirect_to editions_url, notice: 'Edition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edition
      @edition = Edition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edition_params
      params.require(:edition).permit(:author_id, :name, :publisher_id, :universe_id, :title, :binding, :pages, :language)
    end
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/views/editions/_form.html.erb
<%= form_for @edition, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :binding, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :binding, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pages, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :pages, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :language, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :language, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  editions_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/editions/edit.html.erb
<%- model_class = Edition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Edition %></h1>
</div>
<%= render :partial => 'form' %>

app/views/editions/index.html.erb
<%- model_class = Edition -%>
<div class="page-header">
  <h1><%=t '.title', :default => Edition %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:binding) %></th>
      <th><%= model_class.human_attribute_name(:pages) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @editions.each do |edition| %>
      <tr>
        <td><%= edition.id %></td>
        <td><%= edition.name %></td>
        <td><%= edition.title %></td>
        <td><%= edition.binding %></td>
        <td><%= edition.pages %></td>
        <td><%= edition.language %></td>
        <td><%=l edition.created_at, format: :long %></td>
        <td>
          <%= link_to edition_path(edition), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to edition_path(edition), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_edition_path,
            :class => 'btn btn-primary' %>

app/views/editions/new.html.erb
<%- model_class = Edition -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Edition %></h1>
</div>
<%= render :partial => 'form' %>

app/views/editions/show.html.erb
<%- model_class = Edition -%>
<div class="page-header">
  <h1><%=t '.title', :default => Edition %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @edition.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @edition.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:binding) %></dt>
      <dd><pre class="prettyprint"><%= @edition.binding %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:pages) %></dt>
      <dd><pre class="prettyprint"><%= @edition.pages %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:language) %></dt>
      <dd><pre class="prettyprint"><%= @edition.language %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              editions_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_edition_path(@edition), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              edition_path(@edition),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>