config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :authors

  resources :editions

  resources :universes

  resources :entities

  resources :locations

  resources :properties

  resources :publishers

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/entity.rb
class Entity < ActiveRecord::Base
  belongs_to :universe
  has_and_belongs_to_many :locations
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]

  # GET /entities
  # GET /entities.json
  def index
    @entities = Entity.all
  end

  # GET /entities/1
  # GET /entities/1.json
  def show
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit
  end

  # POST /entities
  # POST /entities.json
  def create
    @entity = Entity.new(entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1
  # PATCH/PUT /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to @entity, notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1
  # DELETE /entities/1.json
  def destroy
    @entity.destroy
    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entity
      @entity = Entity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entity_params
      params.require(:entity).permit(:type, :type_id, :universe_id, :name)
    end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.erb
<%= form_for @entity, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :type_id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  entities_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/entities/edit.html.erb
<%- model_class = Entity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Entity %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entities/index.html.erb
<%- model_class = Entity -%>
<div class="page-header">
  <h1><%=t '.title', :default => Entity %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:type_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @entities.each do |entity| %>
      <tr>
        <td><%= entity.id %></td>
        <td><%= entity.type %></td>
        <td><%= entity.type_id %></td>
        <td><%= entity.name %></td>
        <td><%=l entity.created_at, format: :long %></td>
        <td>
          <%= link_to entity_path(entity), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to entity_path(entity), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_entity_path,
            :class => 'btn btn-primary' %>

app/views/entities/new.html.erb
<%- model_class = Entity -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Entity %></h1>
</div>
<%= render :partial => 'form' %>

app/views/entities/show.html.erb
<%- model_class = Entity -%>
<div class="page-header">
  <h1><%=t '.title', :default => Entity %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type) %></dt>
      <dd><pre class="prettyprint"><%= @entity.type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type_id) %></dt>
      <dd><pre class="prettyprint"><%= @entity.type_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @entity.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              entities_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_entity_path(@entity), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              entity_path(@entity),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>