config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :authors

  resources :editions

  resources :universes

  resources :entities

  resources :locations

  resources :properties

  resources :publishers

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/property.rb
class Property < ActiveRecord::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:type, :type_id, :key_name, :value)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for @property, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :type_id, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :key_name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :key_name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :value, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  properties_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/properties/edit.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Property %></h1>
</div>
<%= render :partial => 'form' %>

app/views/properties/index.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => Property %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:type_id) %></th>
      <th><%= model_class.human_attribute_name(:key_name) %></th>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.id %></td>
        <td><%= property.type %></td>
        <td><%= property.type_id %></td>
        <td><%= property.key_name %></td>
        <td><%= property.value %></td>
        <td><%=l property.created_at, format: :long %></td>
        <td>
          <%= link_to property_path(property), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to property_path(property), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_property_path,
            :class => 'btn btn-primary' %>

app/views/properties/new.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Property %></h1>
</div>
<%= render :partial => 'form' %>

app/views/properties/show.html.erb
<%- model_class = Property -%>
<div class="page-header">
  <h1><%=t '.title', :default => Property %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type) %></dt>
      <dd><pre class="prettyprint"><%= @property.type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type_id) %></dt>
      <dd><pre class="prettyprint"><%= @property.type_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:key_name) %></dt>
      <dd><pre class="prettyprint"><%= @property.key_name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:value) %></dt>
      <dd><pre class="prettyprint"><%= @property.value %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              properties_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_property_path(@property), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              property_path(@property),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>